version: '3'
services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: evepls
      POSTGRES_DB: EveHelper
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
            
  pga:
    image: chorss/docker-pgadmin4
    restart: always
    depends_on:
      - pg
    ports:
      - "5050:5050"

#  proxy:
#    restart: "always"
#    build:
#      context:  ./EveHelper.Proxy
#      dockerfile: Dockerfile
#    ports:
#      - "81:80"
      
  #web:
  #    build:
  #      context: ./EveHelper.Web
  #      dockerfile: Dockerfile
  #    environment:
  #      - VIRTUAL_HOST=eh.local
