version: '3'
services:
  pg:
    build:
      context: ./EveHelper.DBImport
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  pga:
    image: chorss/docker-pgadmin4
    restart: always
    depends_on:
      - pg
    ports:
      - "5050:5050"
    environment:
    - VIRTUAL_HOST=pga.eh.local

  mssql:
    image: microsoft/mssql-server-linux
    restart: always
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Ex4mpleP455w0rD!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express

  proxy:
    build:
      context: ./EveHelper.Proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - pga
        
  #web:
  #  build:
  #    context: ./EveHelper.Web
  #    dockerfile: Dockerfile
  #  environment:
  #    - VIRTUAL_HOST=eh.local
