version: '3'
services:
    mongo:
        image: mongo:latest
        container_name: evehelper_db
        ports:
          - "27017:27017"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin
          - MONGO_INITDB_DATABASE=admin
    mongo_web:
        image: mongo-express
        container_name: evehelper_db_web
        links:
          - mongo:mongo
        ports:
          - "8083:8081"
        environment:
          - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
          - ME_CONFIG_MONGODB_ADMINUSERNAME="admin"
          - ME_CONFIG_MONGODB_ADMINPASSWORD="admin"
          - ME_CONFIG_BASICAUTH_USERNAME="admin"
          - ME_CONFIG_BASICAUTH_PASSWORD="admin"
