version: '3'
services:
  mssql:
    image: microsoft/mssql-server-linux
    restart: always
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Ex4mpleP455w0rD!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express

  # proxy:
  #   build:
  #     context: ./EveHelper.Proxy
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - mssql
        
  # web:
  #  build:
  #    context: ./EveHelper.Web
  #    dockerfile: Dockerfile
  #  environment:
  #    - VIRTUAL_HOST=eh.local
