version: '3'
services:
  pg:
    build:
      context: ./EveHelper.DBImport
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example
            
  pga:
    image: chorss/docker-pgadmin4
    restart: always
    depends_on:
      - pg
    ports:
      - "5050:5050"
    environment:
    - VIRTUAL_HOST=pga.eh.local
        
  proxy:
    build:
      context: ./EveHelper.Proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
        
  #web:
  #  build:
  #    context: ./EveHelper.Web
  #    dockerfile: Dockerfile
  #  environment:
  #    - VIRTUAL_HOST=eh.local
