CREATE TABLE [dbo].[crpNPCCorporations] (
    [corporationID]      INT            NOT NULL,
    [size]               CHAR (1)       NULL,
    [extent]             CHAR (1)       NULL,
    [solarSystemID]      INT            NULL,
    [investorID1]        INT            NULL,
    [investorShares1]    INT            NULL,
    [investorID2]        INT            NULL,
    [investorShares2]    INT            NULL,
    [investorID3]        INT            NULL,
    [investorShares3]    INT            NULL,
    [investorID4]        INT            NULL,
    [investorShares4]    INT            NULL,
    [friendID]           INT            NULL,
    [enemyID]            INT            NULL,
    [publicShares]       INT            NULL,
    [initialPrice]       INT            NULL,
    [minSecurity]        FLOAT (53)     NULL,
    [scattered]          BIT            NULL,
    [fringe]             INT            NULL,
    [corridor]           INT            NULL,
    [hub]                INT            NULL,
    [border]             INT            NULL,
    [factionID]          INT            NULL,
    [sizeFactor]         FLOAT (53)     NULL,
    [stationCount]       INT            NULL,
    [stationSystemCount] INT            NULL,
    [description]        VARCHAR (4000) NULL,
    [iconID]             INT            NULL,
    PRIMARY KEY CLUSTERED ([corporationID] ASC),
    CHECK ([scattered]=(1) OR [scattered]=(0))
);

