CREATE TABLE [dbo].[dgmEffects] (
    [effectID]                       INT            NOT NULL,
    [effectName]                     VARCHAR (400)  NULL,
    [effectCategory]                 INT            NULL,
    [preExpression]                  INT            NULL,
    [postExpression]                 INT            NULL,
    [description]                    VARCHAR (1000) NULL,
    [guid]                           VARCHAR (60)   NULL,
    [iconID]                         INT            NULL,
    [isOffensive]                    BIT            NULL,
    [isAssistance]                   BIT            NULL,
    [durationAttributeID]            INT            NULL,
    [trackingSpeedAttributeID]       INT            NULL,
    [dischargeAttributeID]           INT            NULL,
    [rangeAttributeID]               INT            NULL,
    [falloffAttributeID]             INT            NULL,
    [disallowAutoRepeat]             BIT            NULL,
    [published]                      BIT            NULL,
    [displayName]                    VARCHAR (100)  NULL,
    [isWarpSafe]                     BIT            NULL,
    [rangeChance]                    BIT            NULL,
    [electronicChance]               BIT            NULL,
    [propulsionChance]               BIT            NULL,
    [distribution]                   INT            NULL,
    [sfxName]                        VARCHAR (20)   NULL,
    [npcUsageChanceAttributeID]      INT            NULL,
    [npcActivationChanceAttributeID] INT            NULL,
    [fittingUsageChanceAttributeID]  INT            NULL,
    [modifierInfo]                   NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([effectID] ASC),
    CHECK ([disallowAutoRepeat]=(1) OR [disallowAutoRepeat]=(0)),
    CHECK ([electronicChance]=(1) OR [electronicChance]=(0)),
    CHECK ([isAssistance]=(1) OR [isAssistance]=(0)),
    CHECK ([isOffensive]=(1) OR [isOffensive]=(0)),
    CHECK ([isWarpSafe]=(1) OR [isWarpSafe]=(0)),
    CHECK ([propulsionChance]=(1) OR [propulsionChance]=(0)),
    CHECK ([published]=(1) OR [published]=(0)),
    CHECK ([rangeChance]=(1) OR [rangeChance]=(0))
);

